### ISSUE TITLE
Petite mise à jour

### ISSUE THREAD

**Issue by uProtheus** [Vaur/Tutos-Epitech#1]
Une petite mise à jour s'impose je crois (si ce repo est toujours maintenu).

Dans GRUB, selectionnez BLinux (pas la session exam)
tapez e
Rajoutez init=/bin/sh à la fin de la ligne commençant par linux /boot/...
Puis quand tout aura boot (généralement visible quand plus rien ne charge pendant plus de 20s, pour être sur):
loadkeys fr                                  (pour passer le clavier en FR)
mout -o remount,rw /                  (pour pouvoir ecrire le mot de passe (on boot en ReadOnly)
passwd                                       (pour changer le mot de passe)

**Comment by theobch** [comment]
Alors effectivement, cela marche, mais une seule fois: directement après avoir appliqué ces commandes et avoir reboot, oui, nous serons root, mais essaies un autre reboot, et tu verras que le fichier Sudoers se remet à zéro et que le root n'est plus effectif.

**Comment by uProtheus** [comment]
Effectivement, je m'en suis servi pour installer un OS et je ne suis plus retourné dessus. Je vais essayer de voir par quelle méthode ils passent pour faire ça. J'ai aussi remarqué que si tu te root, puis tu sorts du terminal, il est impossible de se reroot

**Comment by theobch** [comment]
Ok, alors je suis root permanent, mais ne me demande(z) pas comment je n'en ai aucune idée...
Juste les étapes par lesquelles je suis arrivé là :
-Je me suis root temporairement grâce à ta méthode décrite plus haut;
-J'ai installé BBQLinux (une super distribution ArchLinux pour le développement Android, elle contient l'ensemble des outils déjà installés, jètes-y un coup d'œil ça vaut vraiment le coup):
-Je retourne sur Blinux pour actualiser le GRUB (je me reroot préalablement) ;
-GRUB bien actualisé, la distribution ne démarre pas (Impossible de trouver le disque sur lors du démarrage, selon la distribution), bref, je désinstalle la distribution;
-Je redémarre sous Blinux pour actualiser le GRUB, et là, surprise je suis encore root...
Voilà, aucune idée du pourquoi ni du comment.

**Comment by alexfeyf** [comment]
Changer une ligne dans le fichier minion permet de désactiver la remise à zero du ficher sudoers.
cd ~/etc/salt/minion 
Changer la ligne salt.blinux.fr en n'importe quoi, nope par exemple

**Comment by Vaur** [comment]
Bonjour,

Ce tuto a été écrit alors que j'étais en Tek1. Notre distribution linux était différente de celle que vous avez. Aujourd'hui je suis en tek4, je n'ai plus le dump de l'école et je ne peux pas non plus le récupérer.

Si vous avez une solution pour mettre à jour ce tuto, n'hésitez pas à m'envoyer un pull request.
